### PR TITLE
WD-3060 - Handle login timeouts

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Upgrade libjuju to 3.1.3.
- Handle login timeouts.

## QA

- If you're using a local dashboard then make sure you're connected to JAAS (the demo service already is).
- Log out if you're logged in and refresh the page.
- Click "Login to the dashboard" but don't do anything on the new tab that opens.
- Wait for at least a minute (this is just long enough to look out the window and start having an existential crisis).
- Now, ignore any feelings that might lead to good and lasting change in your life, knowing you can substitute them with social media and online shopping, and complete the SSO login.
- Go back to the dashboard and there should be a message: "Could not log into controller".

## Details

Fixes: #491.
https://warthogs.atlassian.net/browse/WD-3060

### CODE REVIEW

**Comment by Lukewh** [comment]
On the demo, I don't get any message, just shows the same screen with "Login to the Dashboard" :(. Followed the QA instructions - had an existential crisis and everything.

**Comment by huwshimi** [comment]
@Lukewh that's odd, I just double checked and it's showing up for me on the demo:

Screenshot 2023-04-27 at 9 10 36 am

After a minute did you complete the SSO login? Is it possible you just didn't wait long enough (it needs to be at least a minute)?

**Comment by Lukewh** [comment]
I think it might just be an issue with my account. I'm going to dig in and see if I can unbroke it.

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Pull request merged**
