### PR TITLE
Use relative time in action log

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Change time in the action log to be relative and display the timestamp in a tooltip.
- Update tests to TypeScript/RTL.

## QA

- Go to a model that has action logs (you might need to perform an action for an app).
- Check that the completion time column shows relative dates.
- Hover the date and you should see the exact date/time.

## Details

Fixes: #965.

## Screenshots

Screen Shot 2022-10-24 at 12 19 45 pm

### CODE REVIEW

**Comment by goulinkh** [comment]
Upon running an action, I get this 
image

**Comment by goulinkh** [comment]
For some context here is object in the redux store:
image

**Comment by huwshimi** [comment]
@goulinkh it looks like this branch is displaying the correct relative date, but for some reason the action timestamps returned by Juju (or jujulib) are `0001-01-01T00:00:00Z`.

It would probably be good to check where this date is coming from. I wasn't able to reproduce it (with Juju 2 or 3) so if you still have that model would you mind checking your websocket connection to see if that is what Juju is returning? I don't think we do any date manipulation in jujulib, but it would be good to rule that out.

**Review by goulinkh — APPROVED** [review]
LGTM, this is way more readable :+1: 

FYI I filed an issue for the date edge case value: https://github.com/canonical/jaas-dashboard/issues/1351

**Pull request merged**
