### PR TITLE
Truncate long usernames in the access panel.

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Truncate long usernames in the access panel.
- Migrate tests to RTL.

## QA

- Go to the model list.
- Open the access panel and add a user with a really long name (so that it doesn't fit in the box).
- You should see the username truncated.
- Hover the username and you should see the full name in the tooltip.

## Details

Fixes: #1245.

## Screenshots

Screenshot 2022-10-26 at 11 12 33 am

### CODE REVIEW

**Comment by huwshimi** [comment]
@goulinkh I've fixed the username in the panel but when I went to fix the notification I discovered I'd introduced a bug when I refactored the connections to happen in the middleware, so I'll revisit this PR once I fix that issue.

**Comment by goulinkh** [comment]
@huwshimi is this PR ready for a review?

**Comment by huwshimi** [comment]
> @huwshimi is this PR ready for a review?

I've got a PR up for the new bug I introduced: https://github.com/canonical/jaas-dashboard/pull/1360. Once that lands I'll update this PR.

**Comment by huwshimi** [comment]
@goulinkh I've fixed these issues so this is ready for review again.

Screenshot 2023-01-12 at 9 49 31 am

**Review by goulinkh — APPROVED** [review]
This is looking great!

**Pull request merged**
